#!/usr/bin/env python3

import setuptools


setuptools.setup(
    name="ISC",
    version="0.0.4",
    author="Marius Klein",
    author_email="marius.klein@embl.de",
    #package_dir = {"ISC": "ISC"},
    packages=setuptools.find_packages(include=["ISC*"]),
    description="This package showcases ion suppression correction on single-cell metabolomics datasets generated by SpaceM",
    url="https://github.com/mariusrklein/FDA_project",
    license='MIT',
    entry_points={"gui_scripts": ["ISC=ISC.__main__:main"]},
    python_requires='>=3.7',
    install_requires=["setuptools>=61.0",
        "wheel",
        "bioinfokit",
        "importlib_resources",
        "nbconvert",
        "ipykernel",
        "scanpy>=1.9.1",
        "bbknn",
        "patsy",
        "papermill",
        "ipywidgets",
        "leidenalg",
        # these are actually SpaceM dependencies
        "imageio",
        "metaspace2020",
        "toolz",
        "scikit-image",
        "pyimzml",
        "chardet",
        "pyqt5",
        "SpaceM @ git+https://git.embl.de/mklein/spacem.git",
    ],
    # data_files=[("src/notebook_templates",["ISC/src/notebook_templates/qc.ipynb",
    #                  "ISC/src/notebook_templates/results_analysis.ipynb"])],
    package_data={'ISC': ["src/notebook_templates/qc.ipynb",
        "src/notebook_templates/results_analysis.ipynb"]},
)
