#!/usr/bin/env python3

import setuptools


setuptools.setup(
    name="ISC",
    version="0.0.3",
    author="Marius Klein",
    author_email="marius.klein@embl.de",
    package_dir = {"ISC": "ISC"},
    description="This package showcases ion suppression correction on single-cell metabolomics datasets generated by SpaceM",
    url="https://github.com/mariusrklein/FDA_project",
    license='MIT',
    python_requires='>=3.10',
    install_requires=["setuptools>=61.0",
        "bioinfokit",
        "nbconvert",
        "ipykernel",
        "scanpy>=1.9.1",
        "bbknn",
        "patsy",
        "papermill",
        "ipywidgets",
        "leidenalg",
        "imageio",
        "scikit-image",
        "pyimzml",
        "chardet",
        "pyqt5",
    ],
    data_files=[("src/notebook_templates",["ISC/src/notebook_templates/qc.ipynb",
                     "ISC/src/notebook_templates/results_analysis.ipynb"])],
)
