import sys
import argparse
from ISC.src.ion_suppression import ISC
from ISC.src import const


if __name__ == '__main__':

    parser = argparse.ArgumentParser(prog="ISC", 
                                     description = "this tool performs ion suppression correction on a single-cell metabolomics dataset generated by SpaceM.")

    # Adding optional argument
    parser.add_argument("path", help = "SpaceM folder path")
    parser.add_argument("-c", "--config", help = "Location and name of config file")
    parser.add_argument("-j", "--jobs", help = "set number of jobs for multiprocessing", type=int)
    parser.add_argument("-v", "--verbose", help = "produce more output", action='store_true')

    args = parser.parse_args()
    
    if args.config is not None:
        conf = args.config
    else:
        conf=None
        
    if args.verbose:

        print('Running ion suppression correction with folder "%s"'%args.path)
        if args.config is not None:
            print('Using config file at "%s"'%args.config)
        else:
            print('Using default config:')
            print(const.CONFIG)
    if args.jobs is not None:
        print('Running with %d jobs'%args.jobs)

    
    isc = ISC(source_path = args.path, 
              config = conf,
              n_jobs = args.jobs,
              verbose = args.verbose)
    isc.run()
        
        